### ISSUE TITLE
Does stripe still use this? Last commit in 2013

### ISSUE THREAD

**Issue by bf4** [stripe/poncho#14]

**Comment by mfix-stripe** [comment]
Hey @bf4, sorry about the delay! One team at Stripe is still using this project internally, but we are actively migrating off of it to more modern tech. It is mostly unmaintained, but we of course still monitor for bugs and security issues. We will update this repo with the latest maintenance status once we have fully migrated off of poncho.

**Comment by bf4** [comment]
Thanks!
